Added README and Code of Conduct files
nablab-opencode/miMerendero pull request #6
Opened 2020-11-26 21:37 UTC by marianoaguero

## Description

Added README and Code of Conduct files

## Story/Task/Issue ID
Copy the code number for the planned item that is implemented by this PR.

## How Has This Been Tested?

Open README.md and code_of_conduct.md files.

**Test Configuration**:
* Device Android version:
* Phone Maker:
* Phone Model:

## Checklist:
 - [ ] Code compiles and runs on my devices.
 - [ ] Changes meet acceptance criteria.
 - [ ] Self-review of my own code.
 - [ ] Code is commented where needed.
 - [ ] Conventional commits with meaningful messages.
 - [ ] Changes to the docs.
 - [ ] My changes generate no new warnings.
 - [ ] Added/Changed tests.
 - [ ] All tests pass after changes.
 - [ ] Squash to minimum of commits.
 - [ ] PR title, description and labels for humans.
 - [ ] Reviewer/s assigned.

## Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2020-12-03 22:55 UTC, Andresteve07 requested changes
small things

2020-12-03 22:55 UTC, Andresteve07 commented on code_of_conduct.md
> +[INSERT CONTACT METHOD].
contact email maybe?

2020-12-03 22:55 UTC, Andresteve07 commented on README.md
> +Please make sure to update tests as appropriate.
Please make sure to add and update tests related to your changes.

2020-12-21 22:56 UTC, Andresteve07 approved these changes
all good

2020-12-21 22:59 UTC, miglierinicarlos approved these changes
No veo errores

2020-12-21 23:00 UTC, merged